# Generated by Django 4.0.4 on 2022-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
